language: android
android:
  components:
    - build-tools-28.0.3
    - android-28

notifications:
  email:
    recipients:
      - jacques.hoschtettler@gmx.com
    on_success: always
    on_failure: always

branches:
  only:
    - master

codecov:
  notify:
    require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "header, diff"
  behavior: default
  require_changes: no


after_success:
- bash <(curl -s https://codecov.io/bash)
 CODECOV_TOKEN="07f32d4f-5495-4ca7-bf26-a3b10ed46df7"