language: android
android:
  components:
    - build-tools-28.0.3
    - android-28

notifications:
  email:
    recipients:
      - jacques.hoschtettler@gmx.com
    on_success: always
    on_failure: always

branches:
  only:
    - master

after_success:
- bash <(curl -s https://codecov.io/bash)
