language: android       # To an android app
   	jdk: oraclejdk8     # Use Jdk8
   	email: true         # Email sent when the process is complete

env:
   	# Global Reference Values for the file


   	global:
   	#Android API Version for the code (same as specified in projects build.gradle file)
   	   - ANDROID_API_LEVEL=28
   	#Android API Version for the emulator
       - EMULATOR_API_LEVEL=26
   	#Android Build Tools Version (same as specified in projects build.gradle file)
       - ANDROID_BUILD_TOOLS_VERSION=28.0.3
   	# Android API Version for the target
       - ANDROID_TARGET=android-15
       - ANDROID_ABI=armeabi-v7a
   	#Install Timeout (by default 2min is not enough for slow computers)
       - ADB_INSTALL_TIMEOUT=5 # minutes

android:
  components:
    # Android SDK Tools
      - tools
      - platform-tools
      - tools
    # The BuildTools version used by your project
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    # The SDK version used to compile your project
      - android-$ANDROID_API_LEVEL
    # The SDK version used by emulator
      - android-$EMULATOR_API_LEVEL
    # Specify at least one system image for emulator
      - sys-img-armeabi-v7a-android-$EMULATOR_API_LEVEL
    # Additional components
      - extra-google-google_play_services
      - extra-google-m2repository
      - extra-android-m2repository
      - addon-google_apis-google-$ANDROID_API_LEVEL
      - sys-img-${ANDROID_ABI}-${ANDROID_TARGET}

notifications:
  email:
    recipients:
      - jacques.hoschtettler@gmx.com
    on_success: always
    on_failure: always

branches:
  only:
    - master

before_script:
   	  - chmod +x gradlew
   	#Unit Tests
   	  - ./gradlew build jacocoTestReport assembleAndroidTest
   	#Emulator
   	  - echo no | android create avd --force -n test -t android-$EMULATOR_API_LEVEL --abi armeabi-v7a
   	  - emulator -avd test -no-skin -no-audio -no-window &
   	  - android-wait-for-emulator
      - adb shell input keyevent 82 &

   	#Executes instrumentation tests located in src/androidTests/
   	script:
   	  - ./gradlew build jacocoTestReport assembleAndroidTest
        - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
        - emulator -avd test -no-skin -no-audio -no-window &
        - android-wait-for-emulator
        - adb shell setprop dalvik.vm.dexopt-flags v=n,o=v
   	#Instrumentation Tests
   	- ./gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF android
  # Token is not required with TravisCI
  # CODECOV_TOKEN="07f32d4f-5495-4ca7-bf26-a3b10ed46df7"