language: android
jdk: oraclejdk8

 notifications:
   email:
     recipients:
       - jacques.hoschtettler@gmx.com
     on_success: always
     on_failure: always

 branches:
   only:
     - master

android:
  components:
    - build-tools-28.0.3
    - android-28
 #   - extra-android-m2repository

script:
  - ./gradlew build jacocoTestReport assembleAndroidTest
  #- ./gradlew connectedCheck
  #- ./gradlew jacocoTestReport

after_success:
  - bash <(curl -s https://codecov.io/bash) -cF android

# CODECOV_TOKEN="07f32d4f-5495-4ca7-bf26-a3b10ed46df7"
# This token is not required with Travis